<#
.SYNOPSIS
    Deploys the BYO VNet AI Foundry resources using the hub-spoke network infrastructure.

.DESCRIPTION
    This script automates the deployment of AI Foundry resources that leverage the 
    existing hub-spoke network. It verifies the hub-spoke deployment exists, reads
    the location from it, and deploys the AI Foundry resources.

.PARAMETER ResourceGroupName
    Name of the resource group to create for AI Foundry resources.
    Default: rg-aifoundry-resources

.PARAMETER AutoApprove
    If specified, skips the terraform apply confirmation prompt.

.EXAMPLE
    .\deploy-byo-vnet.ps1
    
.EXAMPLE
    .\deploy-byo-vnet.ps1 -ResourceGroupName "my-foundry-rg" -AutoApprove
#>

param(
    [string]$ResourceGroupName = "rg-aifoundry-resources",
    [switch]$AutoApprove
)

$ErrorActionPreference = "Stop"

# Get script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$CodeDir = Join-Path $ScriptDir "code"
$HubSpokeDir = Join-Path $ScriptDir ".." "hub-spoke-network" "code"

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "BYO VNet AI Foundry Deployment" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Check if hub-spoke-network state exists
$HubSpokeState = Join-Path $HubSpokeDir "terraform.tfstate"
if (-not (Test-Path $HubSpokeState)) {
    Write-Host "ERROR: Hub-spoke network not deployed!" -ForegroundColor Red
    Write-Host "Please deploy hub-spoke-network first:" -ForegroundColor Yellow
    Write-Host "  cd $HubSpokeDir" -ForegroundColor Yellow
    Write-Host "  terraform init" -ForegroundColor Yellow
    Write-Host "  terraform apply" -ForegroundColor Yellow
    exit 1
}

Write-Host "[OK] Hub-spoke network state found" -ForegroundColor Green

# Read location from hub-spoke deployment
Push-Location $HubSpokeDir
try {
    $Location = terraform output -raw resource_group_location 2>$null
    if (-not $Location) {
        Write-Host "ERROR: Could not read location from hub-spoke deployment" -ForegroundColor Red
        exit 1
    }
    Write-Host "[OK] Hub-spoke location: $Location" -ForegroundColor Green
    
    # Also get resource group name for reference
    $HubSpokeRG = terraform output -raw resource_group_name 2>$null
    Write-Host "[OK] Hub-spoke resource group: $HubSpokeRG" -ForegroundColor Green
}
finally {
    Pop-Location
}

# Change to code directory
Push-Location $CodeDir
try {
    # Create/update terraform.tfvars with correct values
    $TfVarsContent = @"
# ============================================
# BYO VNet - AI Foundry Deployment
# ============================================
# Auto-generated by deploy-byo-vnet.ps1
# Hub-spoke network location: $Location

# Path to hub-spoke-network state file
hub_spoke_state_path = "../../hub-spoke-network/terraform.tfstate"

# Resource group name for AI Foundry resources (will be created)
resource_group_name = "$ResourceGroupName"

# Azure region - matches hub-spoke-network
location = "$Location"

# Environment tag
environment = "lab"

# Tags
tags = {
  Project   = "AI Foundry BYO VNet"
  ManagedBy = "Terraform"
}
"@
    
    $TfVarsContent | Out-File -FilePath "terraform.tfvars" -Encoding UTF8
    Write-Host "[OK] Updated terraform.tfvars with location: $Location" -ForegroundColor Green
    Write-Host ""

    # Check ARM_SUBSCRIPTION_ID
    if (-not $env:ARM_SUBSCRIPTION_ID) {
        # Try to get from hub-spoke
        Push-Location $HubSpokeDir
        $SubId = terraform output -raw resource_group_id 2>$null
        if ($SubId -match "/subscriptions/([^/]+)/") {
            $env:ARM_SUBSCRIPTION_ID = $Matches[1]
            Write-Host "[OK] Set ARM_SUBSCRIPTION_ID from hub-spoke: $($env:ARM_SUBSCRIPTION_ID)" -ForegroundColor Green
        }
        Pop-Location
    }
    
    if (-not $env:ARM_SUBSCRIPTION_ID) {
        Write-Host "WARNING: ARM_SUBSCRIPTION_ID not set. You may need to set it:" -ForegroundColor Yellow
        Write-Host '  $env:ARM_SUBSCRIPTION_ID = "your-subscription-id"' -ForegroundColor Yellow
        Write-Host ""
    }

    # Initialize Terraform
    Write-Host ""
    Write-Host "Initializing Terraform..." -ForegroundColor Cyan
    terraform init
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Terraform init failed" -ForegroundColor Red
        exit 1
    }

    # Plan
    Write-Host ""
    Write-Host "Planning deployment..." -ForegroundColor Cyan
    terraform plan -out=tfplan
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Terraform plan failed" -ForegroundColor Red
        exit 1
    }

    # Apply
    Write-Host ""
    if ($AutoApprove) {
        Write-Host "Applying deployment (auto-approved)..." -ForegroundColor Cyan
        terraform apply tfplan
    }
    else {
        Write-Host "Ready to deploy. Review the plan above." -ForegroundColor Yellow
        $confirm = Read-Host "Do you want to apply this plan? (yes/no)"
        if ($confirm -eq "yes") {
            terraform apply tfplan
        }
        else {
            Write-Host "Deployment cancelled." -ForegroundColor Yellow
            exit 0
        }
    }

    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Terraform apply failed" -ForegroundColor Red
        exit 1
    }

    Write-Host ""
    Write-Host "============================================" -ForegroundColor Green
    Write-Host "Deployment Complete!" -ForegroundColor Green
    Write-Host "============================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "AI Foundry resources deployed to: $ResourceGroupName" -ForegroundColor Cyan
    Write-Host "Network infrastructure from: $HubSpokeRG" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "To access AI Foundry:" -ForegroundColor Yellow
    Write-Host "1. Connect to VPN (see hub-spoke-network deployment)" -ForegroundColor Yellow
    Write-Host "2. Access AI Foundry portal via private endpoint" -ForegroundColor Yellow
}
finally {
    Pop-Location
}
